---
title: "Heterogeneity in treatment effects of 'Call to action' using berry-2s method"
author: "Sandeep Gangarapu"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: pdf_document
---
```{r echo=FALSE}
setwd('C:\\Users\\Sandeep Kumar\\Google Drive\\Ed Research\\Heterogenous treatment effects\\git_code\\hte')
source('berry_function.R')
collage_data <- read.csv('C:\\Users\\Sandeep Kumar\\Google Drive\\Ed Research\\Heterogenous treatment effects\\collage_treatment_effect.csv')
control_placeholder <- '1'
egoistic_placeholder <- '2'
equitable_placeholder <- '3'
altruistic_placeholder <- '4'
```

##Altruistic group with number_referrals as target_variable
```{r echo=FALSE}
alt_nr_output <- berry2s(
             data = collage_data,
             control_group_placeholder = control_placeholder,
             treatment_group_placeholder = altruistic_placeholder,
             treatment_variable = "cell",
             target_variable = "number_referrals",
             covariates = c("satisfied","NPS","lastday_purchase_all","num_purchase_all","money_spend_all","survey"),
             covariate_factors = c("cell","satisfied","survey"))
kable(alt_nr_output)
```

##Egoistic group with number_referrals as target_variable
```{r echo=FALSE, eval=FALSE}

ego_nr_output <- berry2s(
  data = collage_data,
  control_group_placeholder = control_placeholder,
  treatment_group_placeholder = egoistic_placeholder,
  treatment_variable = "cell",
  target_variable = "number_referrals",
  covariates = c("satisfied","NPS","lastday_purchase_all","num_purchase_all","money_spend_all","survey"),
  covariate_factors = c("cell","satisfied","survey"))
```

##Equitable group with number_referrals as target_variable
```{r echo=FALSE, eval=FALSE}
equi_nr_output <- berry2s(
  data = collage_data,
  control_group_placeholder = control_placeholder,
  treatment_group_placeholder = equitable_placeholder,
  treatment_variable = "cell",
  target_variable = "number_referrals",
  covariates = c("satisfied","NPS","lastday_purchase_all","num_purchase_all","money_spend_all","survey"),
  covariate_factors = c("cell","satisfied","survey"))
```

##Altruistic group with covertion_rate as target_variable
```{r echo=FALSE, eval=FALSE}
alt_con_output <- berry2s(
  data = collage_data,
  control_group_placeholder = control_placeholder,
  treatment_group_placeholder = altruistic_placeholder,
  treatment_variable = "cell",
  target_variable = "con_rate",
  covariates = c("satisfied","NPS","lastday_purchase_all","num_purchase_all","money_spend_all","survey"),
  covariate_factors = c("cell","satisfied","survey"))
```

##Equitable group with covertion_rate as target_variable
```{r echo=FALSE, eval=FALSE}
equi_con_output <- berry2s(
  data = collage_data,
  control_group_placeholder = control_placeholder,
  treatment_group_placeholder = equitable_placeholder,
  treatment_variable = "cell",
  target_variable = "con_rate",
  covariates = c("satisfied","NPS","lastday_purchase_all","num_purchase_all","money_spend_all","survey"),
  covariate_factors = c("cell","satisfied","survey"))
```

##Egoistic group with covertion_rate as target_variable
```{r echo=FALSE, eval=FALSE}
ego_con_output <- berry2s(
  data = collage_data,
  control_group_placeholder = control_placeholder,
  treatment_group_placeholder = egoistic_placeholder,
  treatment_variable = "cell",
  target_variable = "con_rate",
  covariates = c("satisfied","NPS","lastday_purchase_all","num_purchase_all","money_spend_all","survey"),
  covariate_factors = c("cell","satisfied","survey"))

```

```{r echo=FALSE, eval=FALSE}
write.csv(alt_nr_output, 'C:\\Users\\Sandeep Kumar\\Google Drive\\Ed Research\\Heterogenous treatment effects\\alt_nr_output.csv', row.names = FALSE)
write.csv(ego_nr_output, 'C:\\Users\\Sandeep Kumar\\Google Drive\\Ed Research\\Heterogenous treatment effects\\ego_nr_output.csv', row.names = FALSE)
write.csv(equi_nr_output, 'C:\\Users\\Sandeep Kumar\\Google Drive\\Ed Research\\Heterogenous treatment effects\\equi_nr_output.csv', row.names = FALSE)
write.csv(alt_con_output, 'C:\\Users\\Sandeep Kumar\\Google Drive\\Ed Research\\Heterogenous treatment effects\\alt_con_output.csv', row.names = FALSE)
write.csv(ego_con_output, 'C:\\Users\\Sandeep Kumar\\Google Drive\\Ed Research\\Heterogenous treatment effects\\ego_con_output.csv', row.names = FALSE)
write.csv(equi_con_output, 'C:\\Users\\Sandeep Kumar\\Google Drive\\Ed Research\\Heterogenous treatment effects\\equi_con_output.csv', row.names = FALSE)
```

